title: Jeremy Burgess
description: Professional website of Jeremy Burgess

theme: null  # disable remote theme to allow layout override

defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/custom.css"

# remote_theme: pages-themes/cayman@v0.2.0
 plugins:
    - jekyll-seo-tag
#   - jekyll-remote-theme

author: Jeremy Burgess
